# Generated by Django 4.2.7 on 2024-01-13 12:37

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]
