# Generated by Django 4.2.7 on 2024-01-13 13:21

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_metadata_preview_image_organization_image'),
        ('vector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
                ('index', models.IntegerField(default=-1)),
                ('offset', models.IntegerField(default=-1)),
                ('resource_type', models.CharField(choices=[('pdf', 'pdf'), ('url', 'url')], max_length=3)),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='home.metadata')),
            ],
        ),
    ]
