# Generated by Django 4.2.7 on 2023-12-11 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('language', models.CharField(default='', max_length=256)),
                ('type', models.CharField(default='Other', max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=50)),
                ('states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=32)),
                ('description', models.TextField()),
                ('organization', models.CharField(default='', max_length=256)),
                ('meta_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
