# Generated by Django 4.2.7 on 2023-12-11 21:40

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_metadata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='description_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
