# Generated by Django 4.2.7 on 2023-12-11 22:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_metadata_description_vector_alter_metadata_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_vector'], name='home_metada_descrip_92bd52_gin'),
        ),
    ]
