# Generated by Django 4.2.7 on 2023-12-28 12:11

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_metadata_home_metada_descrip_92bd52_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='metadata',
            name='description_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='meta_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('youtube', 'Youtube')], max_length=10)),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_data', to='home.metadata')),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('ppt', 'PPT'), ('txt', 'TXT'), ('img', 'IMG')], max_length=10)),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_data', to='home.metadata')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
