# Generated by Django 4.2.7 on 2023-12-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vanswer.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_organization_alter_metadata_description_vector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='file',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='type',
        ),
        migrations.AddField(
            model_name='metadata',
            name='category',
            field=models.CharField(choices=[('report', 'Report'), ('case_study', 'Case Study'), ('interview', 'Interview'), ('journal_article', 'Journal Article'), ('journal_edition', 'Journal Edition'), ('study', 'Study'), ('manual', 'Manual'), ('directory', 'Directory'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='metadata',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadata',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='metadata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadata',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('od', 'Odia'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('otr', 'Other')], default='otr', max_length=3),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='states',
            field=vanswer.utils.ChoiceArrayField(base_field=models.CharField(choices=[('ad', 'Andhra Pradesh'), ('ar', 'Arunachal Pradesh'), ('as', 'Assam'), ('br', 'Bihar'), ('cg', 'Chattisgarh'), ('dl', 'Delhi'), ('ga', 'Goa'), ('gj', 'Gujarat'), ('hr', 'Haryana'), ('hp', 'Himachal Pradesh'), ('jk', 'Jammu and Kashmir'), ('jh', 'Jharkhand'), ('ka', 'Karnataka'), ('kl', 'Kerala'), ('ld', 'Lakshadweep Islands'), ('mp', 'Madhya Pradesh'), ('mh', 'Maharashtra'), ('mn', 'Manipur'), ('ml', 'Meghalaya'), ('mz', 'Mizoram'), ('nl', 'Nagaland'), ('od', 'Odisha'), ('py', 'Pondicherry'), ('pb', 'Punjab'), ('rj', 'Rajasthan'), ('sk', 'Sikkim'), ('tn', 'Tamil Nadu'), ('ts', 'Telangana'), ('tr', 'Tripura'), ('up', 'Uttar Pradesh'), ('uk', 'Uttarakhand'), ('wb', 'West Bengal'), ('an', 'Andaman and Nicobar Islands'), ('ch', 'Chandigarh'), ('dnhdd', 'Dadra & Nagar Haveli and Daman & Diu'), ('la', 'Ladakh')], max_length=10), size=32),
        ),
    ]
