# Generated by Django 4.2.7 on 2024-01-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_metadata_preview_image_organization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organization_img', verbose_name='image')),
                ('org', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='org_images', to='home.organization')),
            ],
        ),
    ]
