# Generated by Django 4.2.7 on 2024-01-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orgimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgimages',
            options={'verbose_name': 'Carousel Image', 'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logo'),
        ),
    ]
