# Generated by Django 4.2.7 on 2023-12-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_name_metadata_title_metadata_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='file',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='format',
        ),
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('youtube', 'Youtube')], max_length=10)),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_data', to='home.metadata')),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('ppt', 'PPT'), ('txt', 'TXT'), ('img', 'IMG')], max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.metadata')),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_data', to='home.metadata')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
