# Generated by Django 4.2.7 on 2023-12-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_metadata_options_rename_name_metadata_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='home.organization'),
            preserve_default=False,
        ),
    ]
