# Generated by Django 4.2.7 on 2023-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_metadata_options_rename_type_metadata_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
