# Generated by Django 4.2.7 on 2023-12-28 10:10

from django.db import migrations, models
import vanswer.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_metadata_options_alter_filedata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='organization',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('od', 'Odia'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('otr', 'Other')], default='otr', max_length=3),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='states',
            field=vanswer.utils.ChoiceArrayField(base_field=models.CharField(choices=[('ad', 'Andhra Pradesh'), ('ar', 'Arunachal Pradesh'), ('as', 'Assam'), ('br', 'Bihar'), ('cg', 'Chattisgarh'), ('dl', 'Delhi'), ('ga', 'Goa'), ('gj', 'Gujarat'), ('hr', 'Haryana'), ('hp', 'Himachal Pradesh'), ('jk', 'Jammu and Kashmir'), ('jh', 'Jharkhand'), ('ka', 'Karnataka'), ('kl', 'Kerala'), ('ld', 'Lakshadweep Islands'), ('mp', 'Madhya Pradesh'), ('mh', 'Maharashtra'), ('mn', 'Manipur'), ('ml', 'Meghalaya'), ('mz', 'Mizoram'), ('nl', 'Nagaland'), ('od', 'Odisha'), ('py', 'Pondicherry'), ('pb', 'Punjab'), ('rj', 'Rajasthan'), ('sk', 'Sikkim'), ('tn', 'Tamil Nadu'), ('ts', 'Telangana'), ('tr', 'Tripura'), ('up', 'Uttar Pradesh'), ('uk', 'Uttarakhand'), ('wb', 'West Bengal'), ('an', 'Andaman and Nicobar Islands'), ('ch', 'Chandigarh'), ('dnhdd', 'Dadra & Nagar Haveli and Daman & Diu'), ('la', 'Ladakh')], max_length=10), size=32),
        ),
    ]
