name: Build PG Docker Image

on:
  push:
    branches:
      - master

    paths:
      - 'pg.DockerFile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.folder }}
          file: ./pg.DockerFile
          push: true
          tags: |
            rohittp0/pg-vector:${{ github.sha }}
            rohittp0/pg-vector:latest
